### ISSUE TITLE
HttpMessageTransport Connection Issue

### ISSUE THREAD

**Issue by amikapoor** [neutmute/loggly-csharp#103]
Hi,

Is there any reason why the `Connection: close` header is added at line 24 in `HttpMessageTransport.cs`?

We are using this library for to monitor a web app and a function app on Azure and we are experiencing SNAT port exhaustion as soon as we turn on logging. I believe adding this header does not allow the application to reuse connections.

Also, the default behavior when I POST on Loggly with no headers gives a response header of `Connection: keep-alive`. When I POST with the `Connection: close` header, the return is also `Connection: close`.

Any insight would be appreciated.

Thanks

**Comment by neutmute** [comment]
Hi Amika - If there was a reason then it has been lost in the mists of time. Pull requests are welcome.

**Comment by amikapoor** [comment]
Cool thanks, I'll be happy to do that. Can you please add me as a contributor so I can make a branch/PR?

**Comment by amikapoor** [comment]
Hi @neutmute 

Thanks for the quick response. I have created a PR [here](https://github.com/neutmute/loggly-csharp/pull/104).

Please let me know if you have any questions or concerns.

Thanks

**Comment by amikapoor** [comment]
Hi @neutmute 

Could you please take a look at my PR when you have a chance and let me know what you think?

**Comment by neutmute** [comment]
great. Although thats not how it works. You don't need to be a contributor
to PR

**Comment by amikapoor** [comment]
> great. Although thats not how it works. You don't need to be a contributor to PR
> […](#)

Yup. I realized that after I said it. I went ahead and made the PR the proper way. I’ve never contributed to a public repo but now I know how to! Thanks
