### ISSUE TITLE
Nuget Publishing

### ISSUE THREAD

**Issue by amikapoor** [neutmute/loggly-csharp#106]
@neutmute 

Hi again

Any idea why the nuget for `loggly-csharp` isn't being published but the nuget for `loggly-csharp-config` is? It seems like this problem has existed for a couple versions now. I noticed in the log of the master build, it says the nugets for both were published with versions `4.6.1.88` but looking at nuget, `loggly-csharp` has been stuck on `4.6.1.82` for a few releases now but `loggly-csharp-config` has been building and publishing just fine with every merge.

Thanks

**Comment by amikapoor** [comment]
I figured it out. The project does not build when targeting netstandard1.5. @snakefoot and @neutmute  you may want to take a look at this [PR](https://github.com/neutmute/loggly-csharp/pull/107).

Thanks

**Comment by neutmute** [comment]
merged
