### ISSUE TITLE
Potential code improvement UDP transport

### ISSUE THREAD

**Issue by LarsWesselius** [neutmute/loggly-csharp#120]
In this code here;
https://github.com/neutmute/loggly-csharp/blob/0c04738f861417083ca480c12bada900a26b1d06/source/Loggly/Transports/SyslogTransports/SyslogUdpTransport.cs#L46

Wouldn't it be better to use the overload specified here? https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.udpclient.sendasync?view=net-6.0#system-net-sockets-udpclient-sendasync(system-byte()-system-int32-system-string-system-int32)

Then you don't need to do the DNS lookup yourself and in that overload there's some code to verify family in case of multiple IP addresses.

**Comment by snakefoot** [comment]
@LarsWesselius Have created #121, you are wellcome to review

**Comment by snakefoot** [comment]
You can find pre-release nuget-packages here, that you can try using a local-nuget-repo-folder:

https://ci.appveyor.com/project/neutmute/loggly-csharp/builds/43279738/artifacts

**Comment by snakefoot** [comment]
@LarsWesselius https://www.nuget.org/packages/loggly-csharp v4.6.1.114 has been released.
