### ISSUE TITLE
App.Config settings not working since commit 8553c72

### ISSUE THREAD

**Issue by gouranga** [neutmute/loggly-csharp#123]
Conditional compilation symbol `FEATURE_SYSTEM_CONFIGURATION` was removed when project was migrated to newer `csproj` format.
8553c72f462c151c30affa87267cbcadc1a0dfb9

So now, section `Configuration via app.Config` in `readme.md` is not working anymore.
Latest nuget package with working functionality is 4.6.1.92.

P.S. `FEATURE_SYSTEM_ENVIRONMENT_OSVERSION` was also removed.

**Comment by snakefoot** [comment]
@gouranga PullRequests are always wellcome to restore the functionality.

**Comment by snakefoot** [comment]
Created  #124 to restore the functionality

**Comment by gouranga** [comment]
@snakefoot sorry, i was going to make pr in a few days :-)
