### ISSUE TITLE
Is there any reason for httpwebrequest over httpclient async?

### ISSUE THREAD

**Issue by samirahmed** [neutmute/loggly-csharp#24]
https://github.com/neutmute/loggly-csharp/blob/master/source/Loggly/Transports/HttpTransports/HttpMessageTransport.cs#L38

Is there any reason the async HttpClient isn't being used over synchronous `HttpWebRequest`?

If there is no reason, I will be willing to make the changes necessary.

**Comment by neutmute** [comment]
Hi there. Not sure I get your meaning? From memory the transports are synchronous and the async happens in the layer above

**Comment by neutmute** [comment]
[fuzzy memory] The UDP transport didn't have async [/fuzzy memory] and so the async is done via a Task<LogResponse> - see here
https://github.com/neutmute/loggly-csharp/blob/master/source/Loggly/LogglyClient.cs#L20

Hence the transport underneath can be synchronous
