### ISSUE TITLE
Loggly Token configuration via appSettings

### ISSUE THREAD

**Issue by miketrionfo** [neutmute/loggly-csharp#30]
Love the library.  Just wondering if support for reading the customerToken from the appSettings list in the app.config or web.config file could easily be added?  This makes protecting a production customerToken very easy because that value would never have to be committed to source control. If running in Azure, that token can be easily stored in the Azure Portal.

Any tips on where that can be supported would be helpful.  

Thanks!

**Comment by neutmute** [comment]
If I understand correctly you don't want the customerToken in your appConfig but will stash it somewhere else. eg: An environment variable in the vain of ASP.NET 5. 

What you can do is use a fake customerToken say in app.config [LogglyConfig.cs](https://github.com/neutmute/loggly-csharp/blob/master/source/Loggly.Config/LogglyConfig.cs#L34) and then read & poke in the real one at app startup. Does that help?

**Comment by miketrionfo** [comment]
That could work, but It's the read & poke that I can't easily figure out how to do at startup.  How do I set the token at startup in code?

**Comment by neutmute** [comment]
Read: You need to get your token from whatever store you wish to use
Poke:  here is an example of manipulating the config [LogglyExample.cs, line 61](https://github.com/neutmute/loggly-csharp/blob/master/source/Loggly.Example/LogglyExample.cs#L61)

Beyond that, I can't help you. Good luck!
