### ISSUE TITLE
Keys

### ISSUE THREAD

**Issue by shawnemullen** [neutmute/loggly-csharp#33]
It appears that I am forced to submit my log data with a key. - logentry.Add("key","what ever").

How do  I log data without the key?  I like to shape my own data.  I don't like 3rd parties adding data to my log unless I have a way to turn it off.

**Comment by neutmute** [comment]
I don't understand your question. If you don't want to add keys, don't add them?

**Comment by shawnemullen** [comment]
I'll try to do a better job.

logEvent.Data.Add("context", new GlimmerWingPony());
_loggly.Log(logEvent);

let's assume GlimmerWingPony() looks like:

{
  "userId":"123",
 "username":"shawn"
}

The above call to loggly produces the following in the log:

{
  "context":{
    {
      "userId":"123",
     "username":"shawn"
    }
  }
}

The key "context" is added to the message I want to log.  I want to control what is added to the log.  I want

{
  "userId":"123",
 "username":"shawn"
}

to be all that is added.  No key.

**Comment by neutmute** [comment]
I see. Having a quick look at the code the key/value looks baked into the architecture (`IMessage`) as a way to guide consumers on how to attach multiple pieces of data.

It doesn't appear necessary though in that the LogglyClient can serialize any Data object via `ToJson(object value)`.

Perhaps the logglyClient should be updated to accept an `ILogglyEvent`  and consumers like yourself could implement a generic `LogglyEvent<GlimmerWingPony> : ILogglyEvent` which sets the type of the data. 

Make sense?

**Comment by shawnemullen** [comment]
Yes.  Actually, since my last post, i started working on a solution.

Thanks for your quick reply.

Shawn Mullen

**Comment by shawnemullen** [comment]
There were two ways I was able to get this to work the way I wanted.

1. In my custom class that inherits from IMessageData, I decorate the KeyList property with [JsonIgnore].  

This was the easiest way, but it is not ideal because the only reason it works is because I know the inner workings of the code and I know you use NewtonSoft.  So it sort of violates the idea of encapsulation... maybe :)

2.  Modify IMessageData and change KeyList from a property to a method.

This, I think, is better because everything works like it did before, but if I create a custom object and assign it to the LogEntry.Data property (as in the LogglyExamples), then the key is not serialized with the object.  Seems to me this allows for both ways of logging.

For now, I am opting to use the first solution that way I can use your code out-of-the-box.  However, if you decide to implement a solution for this issue, I think it would be worth it.

**Comment by neutmute** [comment]
stale
