### ISSUE TITLE
Allow specifying loggly key in LogglyClient ctor

### ISSUE THREAD

**Issue by mwhouser** [neutmute/loggly-csharp#35]
I am upgrading from 2.5.1 and the new ctor does not allow me to specify the Loggly access key.

Please restore this behaviour. I need to be able to have multiple `LogglyClient` objects each with different keys.

**Comment by neutmute** [comment]
Hi Matt - I don't have a lot of time at the moment for this. PR happily accepted.

**Comment by neutmute** [comment]
stale
