### ISSUE TITLE
Syslog TCP transport should reuse connection

### ISSUE THREAD

**Issue by mattc-lh** [neutmute/loggly-csharp#38]
**Problem**
The Syslog TCP transports currently establish a new connection (and for SyslogSecure, re-authenticate for TLS) for each log event, which can quickly spiral out of control for a high logging rate. 
- SyslogTransportBase provides a bulk-send method, but implements it by serially calling its individual-send method.
- For each individual send, SyslogTcpTransport.Send(SyslogMessage) creates a new TCP client (for which SyslogSecureTransport additionally performs a 2-trip TLS connection authentication).

**Suggestion**
Could we establish & reuse a single connection, allowing efficient streaming of events without overhead? To support concurrency, this would likely require us to add a queue to the transport.

**Workaround**
The HTTPS transport can be used, as long as events are sent in bulk with appropriate batching (since each HTTPS POST requires a 2-round-trip authentication).

**Comment by mattc-lh** [comment]
This feels like a potentially risky change (but important for any Syslog users)... so I figured it'd be best to have someone more familiar with the codebase and context do this. We've decided to continue using the HTTPS transport for now (with batching), but Syslog streaming support would be great. Thank you in advance for anyone who can invest in this!

**Comment by snakefoot** [comment]
A simple solution could be to async await a SemaphoreSlim, so only one task is allowed to handle the TcpClient.

Maybe something like this:

```
class SyslogTcpTransport : SyslogTransportBase
{
     SemaphoreSlim _mutex = new SemaphoreSlim(1);
     TcpClient _tcpClient;
     Stream _networkStream;

     protected override async Task Send(SyslogMessage syslogMessage)
     {
          byte[] messageBytes = syslogMessage.GetBytes();
          await _mutex.WaitAsync().ConfigureAwait(false);

          try
          {
                  if (_tcpClient == null || _networkStream == null)
                  {
                      var client = new TcpClient();
                      client.NoDelay = true;
                      await tcpClient.ConnectAsync(Hostname, LogglyConfig.Instance.Transport.EndpointPort).ConfigureAwait(false);
                      _networkStream = await GetNetworkStream(client).ConfigureAwait(false);
                  }

                  await _networkStream.WriteAsync(messageBytes, 0, messageBytes.Length).ConfigureAwait(false);
                  await _networkStream.FlushAsync().ConfigureAwait(false);
          }
          catch (Exception ex)
          {
               var tcpClient = _tcpClient;
               _tcpClient = null;
               tcpClient?.Dispose();
          }
          finally
          {
                _mutex.Release();
          }
     }
}
```

I guess somewhere in the framework there should be some kind of Close-method on TransportBase.

**Comment by NiklasArbin** [comment]
Apart from the tcp connection not being reused I'm a bit curious why the ConnectAsync called is not awaited and is using .Wait() and this outside of the try/catch block.

**Comment by neutmute** [comment]
Hey there - happy to merge a PR if this can be optimised

**Comment by neutmute** [comment]
I had the same problem - updated the .net standard packages and tweaked `ps1` - builds now and have published your change to nuget. Thanks for the contribution!

**Comment by NiklasArbin** [comment]
#77

**Comment by NiklasArbin** [comment]
This issue can be closed
