### ISSUE TITLE
Trying to open project in Visual Studio 2015

### ISSUE THREAD

**Issue by anthonylamark** [neutmute/loggly-csharp#44]
Hi,
I am getting the errors (below) when opening loggly.sln in Visual Studio 2015.

C:\Users\administrator.CONTOSO\Downloads\loggly-csharp-develop\source\NetStandard\Loggly.Config\Loggly.Config.NetStandard.xproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\administrator.CONTOSO\Downloads\loggly-csharp-develop\source\NetStandard\Loggly.Config\Loggly.Config.NetStandard.xproj

C:\Users\administrator.CONTOSO\Downloads\loggly-csharp-develop\source\NetStandard\Loggly\Loggly.NetStandard.xproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\administrator.CONTOSO\Downloads\loggly-csharp-develop\source\NetStandard\Loggly\Loggly.NetStandard.xproj

C:\Users\administrator.CONTOSO\Downloads\loggly-csharp-develop\source\NetStandard\Loggly.Tests\Loggly.Tests.NetStandard.xproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\administrator.CONTOSO\Downloads\loggly-csharp-develop\source\NetStandard\Loggly.Tests\Loggly.Tests.NetStandard.xproj

**Comment by neutmute** [comment]
Hi there- you need the latest VS2015 tooling

 https://www.microsoft.com/net/core#windows.
