### ISSUE TITLE
The dll is not signed

### ISSUE THREAD

**Issue by JoseTiagoCarvalho** [neutmute/loggly-csharp#46]
Can you please sign the dll, as the project i'm working at requires that.

**Comment by neutmute** [comment]
Hi there. Do you mean strong name key? I'm happy to accept a PR with the *.snk in the repo. Anything else won't work that well with the automated build.
Note: The PR must build correctly on myget to be accepted.

**Comment by JoseTiagoCarvalho** [comment]
Yes, you are right, i meant strong name. Shouldn't your team create a *.snk for your company?

**Comment by JoseTiagoCarvalho** [comment]
Like for instance on the package you have to integrate with Serilog (https://github.com/serilog/serilog-sinks-loggly/pull/6#event-870327760). I guess it must be managed by your team as well, right?

For the "serilog-sinks-loggly" package was used an *.snk from Serilog, but for this one i would suggest create one for Loggly, what do you think?

**Comment by neutmute** [comment]
There is no team :) I'm just a guy that took over the project when I needed some changes to the loggly-csharp for my own companies purposes

This is not an official loggly client

**Comment by neutmute** [comment]
Agree that there should be a loggly-csharp *.snk and not use SeriLogs. So your PR should check in a new *.snk into `SolutionItems` and then modify `build.ps1` to sign the assemblies during the build. It can be added into the *.csproj too I guess but the `build.ps1` is the important thing for nuget packages.

How does that sound?

**Comment by JoseTiagoCarvalho** [comment]
Sounds perfect to me. I Will do the change tomorrow and then add a pull request, ok.

Thanks for then feedback.
