### ISSUE TITLE
Retarget to NetStandard 1.3

### ISSUE THREAD

**Issue by 4ux-nbIx** [neutmute/loggly-csharp#48]
Hi, could you please retarget NetStandard libraries to version 1.3. This will cover most .Net platforms.

Here's the link with compatibility matrix:
https://docs.microsoft.com/en-us/dotnet/articles/standard/library

**Comment by neutmute** [comment]
Hey there - so to confirm you want to downgrade from NetStandard 1.5 to 1.3?

**Comment by 4ux-nbIx** [comment]
Well, I wouldn't call it a downgrade. This will just reduce the amount of .Net APIs available, but will extend the number of supported platforms, UWP for example. I'd love to use loggly in my UWP apps...

**Comment by neutmute** [comment]
I confess I find the .net standard stuff confusing. the way I read the table in your link, UWP 10 is supported from 1.4 forward and not before. or is that reading it wrong?

**Comment by 4ux-nbIx** [comment]
No, 1.4 is the highest supported version by UWP. Higher versions will be supported in later UWP versions, i.e. post 10.0 aka vNext.

**Comment by 4ux-nbIx** [comment]
Basically, 1.0 supports everything, 
1.3 drops Windows 8.1 and beyond, Windows Phone 8.1 and beyond and Windows Phone Silverlight. 
1.5 drops UWP and .Net Framework beyond 4.6.2 and etc.

**Comment by neutmute** [comment]
ok well if you can restarget to 1.3 and it all still works then I'll happy merge that PR. Perhaps dogfood your branch first to make sure its all good

**Comment by 4ux-nbIx** [comment]
I already tried, and it works except for one thing - Environment.MachineName is not available in NetStandard 1.3. Bu I think we can simply exclude the Tag class that's using it...
And there's another problem. I only have the latest VS 2017 RC installed so when I open the source code it converts xproj files to csproj and leaves me no other option. Are you ok with that?

**Comment by neutmute** [comment]
Perhaps in that case it might be best if you maintain a private fork with your changes. I would assume most people aren't on RC yet. You can use myget to easily wire up the build.ps1 and produce nuget packages for your project.

**Comment by 4ux-nbIx** [comment]
ah, ok... Never mind. I decided to use Application Insights instead :)

**Comment by Rambalac** [comment]
@4ux-nbIx Indeed, easiest solution.
