### ISSUE TITLE
Support log level in conf

### ISSUE THREAD

**Issue by dasjestyr** [neutmute/loggly-csharp#51]
I'd like to see a way to set the logging level by configuration file. For example, I have configuration transforms based on the build configuration. Right now I have to do it in code using precompiler logic which is kind of gross and it'd be a lot easier via config.

**Comment by neutmute** [comment]
Hi there - To clarify you want to globally set every log message you issue to be `info` or `warn` ?

**Comment by dasjestyr** [comment]
Since Loggly has indexing limits (e.g. 1GB/day for me), I'd only want that logging level to apply to the loggly sink. Is that what you mean?

**Comment by neutmute** [comment]
Are you using Nlog or some other logging framework to actually do the logging? I think you would solve this by specifying the config in your nlog target say

eg: NLog - https://github.com/neutmute/nlog-targets-loggly

**Comment by neutmute** [comment]
stale
