### ISSUE TITLE
.Net Core Support for Latest Release

### ISSUE THREAD

**Issue by jmhpinto** [neutmute/loggly-csharp#54]
When i'm adding the latest release, it says that is not compatible with .net core 

![image](https://cloud.githubusercontent.com/assets/24326073/26301826/3df5a61a-3eda-11e7-9fec-c0c0a4ea35b1.png)

**Comment by neutmute** [comment]
I was messing about trying to get it to build in vs2017 (see the feature branch) and disabled .net core while trying to get it running and now it is in a broken state. i was hoping you were using the full fx version :)

Do you want to have a poke around and see if you can fix the build? I'm not current on .NET Standard/ Asp.net core at the moment.

you will need to at least uncomment these entries
https://github.com/neutmute/loggly-csharp/blob/develop/source/Loggly.Config/Loggly.Config.nuspec
https://github.com/neutmute/loggly-csharp/blob/develop/source/Loggly/Loggly.nuspec

and make it so the build script works on appveyor...create an account and import a build and it should repro how it is failing currently on my build...

https://ci.appveyor.com/project/neutmute/loggly-csharp

Bit short on time at the moment to do this myself

**Comment by DzmitryZubialevich** [comment]
I've checked the latest nuget package and now it supports net standard 1.5. Can be closed?

**Comment by jmhpinto** [comment]
Yes, sorry but i couldn't help you, i did not had time also and no knowledge about AppVeyor...
