### ISSUE TITLE
Exception in the json serialization while serializing exceptions (.NET Core 1.1)

### ISSUE THREAD

**Issue by tamirdresher** [neutmute/loggly-csharp#60]
Hi

When running inside an ASP.NET Core application and logging an exception, we get the following exception:

```
Newtonsoft.Json.JsonSerializationException: 'Self referencing loop detected for property 'Module' with type 'System.Reflection.RuntimeModule'. Path 'Exception.TargetSite.Module.Assembly.EntryPoint'.'
```
this happening inside the  ```LogglyClient.ToJson(object value) ```
The exception is swallowed silently, and the log message doesn't reach loggly 

The best way to avoid it is by changing the Json serializer configuration and ignore such cases http://www.newtonsoft.com/json/help/html/ReferenceLoopHandlingIgnore.htm

However this will affect every value serialized to loggly (and not just exceptions)
If this is a reasonable solution, i can send a PR.

**Comment by neutmute** [comment]
seems ok to me since the alternative is silent swallowing. PR welcome!

**Comment by tamirdresher** [comment]
Is it ok if i close this issue?

**Comment by neutmute** [comment]
done
