### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by rajeshrajput123** [neutmute/loggly-csharp#70]
var config = LogglyConfig.Instance;
            config.CustomerToken = "xyz";
            config.ApplicationName = "MyApp";
            config.Transport.EndpointHostname = "logs-01.loggly.com";
            config.Transport.EndpointPort = 443;
            config.Transport.LogTransport = LogTransport.Https;
            var ct = new ApplicationNameTag();
            ct.Formatter = "application-{0}";
            config.TagConfig.Tags.Add(ct);

please help ,
can you tell me ,how to use this code using .config file ,
so that code will be written less ,
please explain

**Comment by neutmute** [comment]
Hi Rajesh - the readme.md has examples of config. Check the configuration classes and they reveal how to do via config. Anything missing that can't be done via  config- happy to see a PR
