### ISSUE TITLE
Netstandard support issue with System.Net.Http

### ISSUE THREAD

**Issue by MiguelAlho** [neutmute/loggly-csharp#90]
I've been looking into @mbp 's PR in the Serilog.Sinks.Loggly repo (https://github.com/serilog/serilog-sinks-loggly/pull/50) related to a package upgrade. It unfortunately fails for the NetCoreApp1.0 version ( https://ci.appveyor.com/project/serilog/serilog-sinks-loggly/builds/27012925/tests ) to to a System.Net.Http Assembly version binding issue.

I noticed that the projects are "duplicated", seperating the library compilation for NetStandard and Full Framework versions. AFAIK, this can be done in the same project file - I do this frequently for internal projects. I wouldn't mind working a bit on this to reduce the project count, if it makes sense, but I would like to get some context on the reasoning for the approach.

The only thing I can see at the moment that could hinder the effort would be the .csd generation. Most of the rest could be defined in a single project file per lib, and the packages could be generated from the same source .csproj files, or defer to the current nuspec file.

The nuspec file does have some outdated refs (which might be the cause for the issue in the sink's build). I've created https://github.com/neutmute/loggly-csharp/pull/89 to review this.

**Comment by neutmute** [comment]
Hey Miguel - I'm not really active in this project any more as I'm not using it at my current site.
I don't recall the context of how/why it was setup like this.
Happy to take any PRs you think will improve it.

**Comment by snakefoot** [comment]
@MiguelAlho Resolved with #89 ?

**Comment by MiguelAlho** [comment]
@snakefoot yeap. Closing this for now. The other ideas that I had related to project organization I'm going to have to leave in stand by for now.
